Create wftpl_iam_-_groups_management_template.yaml
Dynatrace/Dynatrace-workflow-samples pull request #24
Opened 2024-08-23 15:40 UTC by imrankhan4z

Added a sample workflow to add IAM groups.

2024-08-25 05:54 UTC, grabnerandi requested changes
Hi. Can you also add a readme that explains workflow? Have a look at some of the other examples in the samples folder. all of them have a readme

2024-08-26 16:42 UTC, imrankhan4z commented
Added the readme file. Please check.

2024-08-28 14:34 UTC, grabnerandi approved these changes

2024-08-28 14:36 UTC, grabnerandi commented
Need one more approval for this review from the maintainers.
For reference - here the link to the LinkedIn Post from Imran who triggered this addition: https://www.linkedin.com/posts/imrankhan4z_dynatrace-saas-workflow-activity-7232411165534953483-7qnt?utm_source=share&utm_medium=member_desktop

2024-08-28 14:42 UTC, miigwi approved these changes

2024-08-28 14:42 UTC, merged